In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [95]:
data= pd.read_csv("crimes_fti.csv")

# Data Description

1. Display shape of the data
2. Display top 20 rows
3. Display data types
4. Display statistical properties like MCT and Dispersion
5. Check for Null Values

In [96]:
data.shape

(65535, 17)

In [97]:
data.head(20)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182080058,2403,Disorderly Conduct,DISTURBING THE PEACE,E18,495,NaN,3/10/18 20:13,2018,10,Wednesday,20,Part Two,ARLINGTON ST,42.262608,-71.121186,"(42.26260773, -71.12118637)"
1,I182080053,3201,Property Lost,PROPERTY - LOST,D14,795,NaN,30/08/2018 20:00,2018,8,Thursday,20,Part Three,ALLSTON ST,42.352111,-71.135311,"(42.35211146, -71.13531147)"
2,I182080052,2647,Other,THREATS TO DO BODILY HARM,B2,329,NaN,3/10/18 19:20,2018,10,Wednesday,19,Part Two,DEVON ST,42.308126,-71.076930,"(42.30812619, -71.07692974)"
3,I182080051,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,92,NaN,3/10/18 20:00,2018,10,Wednesday,20,Part One,CAMBRIDGE ST,42.359454,-71.059648,"(42.35945371, -71.05964817)"
4,I182080050,3122,Aircraft,AIRCRAFT INCIDENTS,A7,36,NaN,3/10/18 20:49,2018,10,Wednesday,20,Part Three,PRESCOTT ST,42.375258,-71.024663,"(42.37525782, -71.02466343)"
5,I182080049,1402,Vandalism,VANDALISM,C11,351,NaN,2/10/18 20:40,2018,10,Tuesday,20,Part Two,DORCHESTER AVE,42.299197,-71.060470,"(42.29919694, -71.06046974)"
6,I182080048,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,NaN,ABC,NaN,3/10/18 20:16,2018,10,Wednesday,20,Part Three,NaN,42.320734,-71.056764,"(42.32073413, -71.05676415)"
7,I182080047,3301,Verbal Disputes,VERBAL DISPUTE,B2,603,NaN,3/10/18 19:32,2018,10,Wednesday,19,Part Three,TREMONT ST,42.333807,-71.103778,"(42.33380683, -71.10377843)"
8,I182080045,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,543,NaN,3/10/18 19:27,2018,10,Wednesday,19,Part Two,AVILA RD,42.256145,-71.128025,"(42.25614494, -71.12802506)"
9,I182080044,3410,Towed,TOWED MOTOR VEHICLE,D4,621,NaN,3/10/18 20:00,2018,10,Wednesday,20,Part Three,COMMONWEALTH AVE,42.348866,-71.089363,"(42.34886600, -71.08936284)"
10,I182080043,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,D14,750,NaN,3/10/18 19:33,2018,10,Wednesday,19,Part Three,FOSTER ST,42.344323,-71.157784,"(42.34432328, -71.15778368)"
11,I182080042,706,Auto Theft,AUTO THEFT - MOTORCYCLE / SCOOTER,E13,582,NaN,1/10/18 20:00,2018,10,Monday,20,Part One,BYNNER ST,42.323244,-71.108923,"(42.32324363, -71.10892316)"
12,I182080041,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,E18,484,NaN,3/10/18 17:18,2018,10,Wednesday,17,Part Three,BELNEL RD,42.260599,-71.103061,"(42.26059891, -71.10306140)"
13,I182080040,3115,Investigate Person,INVESTIGATE PERSON,B3,427,NaN,3/10/18 8:00,2018,10,Wednesday,8,Part Three,ELIZABETH ST,42.279865,-71.087983,"(42.27986526, -71.08798275)"
14,I182080039,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,B3,469,NaN,3/10/18 19:58,2018,10,Wednesday,19,Part Three,FOTTLER RD,42.277919,-71.096406,"(42.27791927, -71.09640610)"
15,I182080038,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,NaN,XYZ,NaN,3/10/18 19:30,2018,10,Wednesday,19,Part Three,NaN,42.315961,-71.090426,"(42.31596119, -71.09042564)"
16,I182080037,2647,Other,THREATS TO DO BODILY HARM,C11,385,NaN,3/10/18 18:35,2018,10,Wednesday,18,Part Two,HALLET ST,42.280767,-71.047365,"(42.28076737, -71.04736497)"
17,I182080035,2647,Other,THREATS TO DO BODILY HARM,B2,326,NaN,3/10/18 19:56,2018,10,Wednesday,19,Part Two,DUNKELD ST,42.312778,-71.075629,"(42.31277782, -71.07562922)"
18,I182080034,3115,Investigate Person,INVESTIGATE PERSON,D4,626,NaN,3/10/18 18:41,2018,10,Wednesday,18,Part Three,KILMARNOCK ST,42.342681,-71.099377,"(42.34268073, -71.09937714)"
19,I182080031,3108,Fire Related Reports,"FIRE REPORT - HOUSE, BUILDING, ETC.",C11,338,NaN,3/10/18 18:18,2018,10,Wednesday,18,Part Three,NAVILLUS TER,42.309988,-71.062131,"(42.30998781, -71.06213111)"

In [98]:
data.dtypes

INCIDENT_NUMBER         object
OFFENSE_CODE             int64
OFFENSE_CODE_GROUP      object
OFFENSE_DESCRIPTION     object
DISTRICT                object
REPORTING_AREA          object
SHOOTING                object
OCCURRED_ON_DATE        object
YEAR                     int64
MONTH                    int64
DAY_OF_WEEK             object
HOUR                     int64
UCR_PART                object
STREET                  object
Lat                    float64
Long                   float64
Location                object
dtype: object

In [99]:
data.describe()

,OFFENSE_CODE,YEAR,MONTH,HOUR,Lat,Long
count,65535.000000,65535.000000,65535.000000,65535.000000,61271.000000,61271.000000
mean,2352.644083,2017.992859,5.743282,13.055543,42.149419,-70.803888
std,1174.988899,0.099948,2.250567,6.278597,2.728613,4.413944
min,111.000000,2015.000000,1.000000,0.000000,-1.000000,-71.178674
25%,1102.000000,2018.000000,4.000000,9.000000,42.296934,-71.097074
50%,3006.000000,2018.000000,6.000000,14.000000,42.325528,-71.077610
75%,3202.000000,2018.000000,8.000000,18.000000,42.348209,-71.062563
max,3831.000000,2018.000000,12.000000,23.000000,42.395042,-1.000000

In [100]:
data.describe(include="object")

,INCIDENT_NUMBER,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,DAY_OF_WEEK,UCR_PART,STREET,Location
count,65535,65535,65535,65022,65535,184,65535,65535,65518,64433,65535
unique,58233,60,179,12,880,1,47974,7,4,3281,11428
top,I182065208,Motor Vehicle Accident Response,SICK/INJURED/MEDICAL - PERSON,B2,,Y,19/07/2018 00:00,Friday,Part Three,WASHINGTON ST,"(0.00000000, 0.00000000)"
freq,10,7572,4595,10022,4689,184,16,9975,33755,3022,4264

In [101]:
data.isnull().sum()

INCIDENT_NUMBER            0
OFFENSE_CODE               0
OFFENSE_CODE_GROUP         0
OFFENSE_DESCRIPTION        0
DISTRICT                 513
REPORTING_AREA             0
SHOOTING               65351
OCCURRED_ON_DATE           0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
UCR_PART                  17
STREET                  1102
Lat                     4264
Long                    4264
Location                   0
dtype: int64

# Dealing with Data Quality Problems

1. Display values counts of all unique values in a column ( All columns)
2. Detect values which are incorrect
3. Handle all such incorrect values ( Only one or two columns may have incorrect values)
4. Replace all incorrect values with NaN
5. Remove all the records having Null / NaN Values
6. Remove all the columns which have more that 50 % null values

In [102]:
data["INCIDENT_NUMBER"].value_counts().unique()

array([10,  7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [135]:
for col in data.columns:
    print(col)
    print(data[col].value_counts())
    print()

INCIDENT_NUMBER
I182031562    6
I182051210    6
I182037657    5
I182058835    5
I182049671    5
I182044393    5
I182031717    4
I182077113    4
I182036730    4
I182052602    3
I182045071    3
I182038763    3
I182033779    3
I182044546    3
I182033510    3
I182019313    3
I182014658    3
I182055198    3
I182053414    2
I182062810    2
I182066420    2
I182074372    2
I182070806    2
I182067317    2
I182035240    2
I182056227    2
I182074638    2
I182053289    2
I182024815    2
I182011931    2
             ..
I182022623    1
I182045765    1
I182028394    1
I182031968    1
I182064056    1
I182060309    1
I182026805    1
I182023966    1
I182011422    1
I182064699    1
I182013270    1
I182058179    1
I182070720    1
I182022093    1
I182024317    1
I182033040    1
I182070974    1
I182064057    1
I182075690    1
I182060366    1
I182064331    1
I182051203    1
I182068876    1
I182052365    1
I182044559    1
I182060953    1
I182022956    1
I182043486    1
I182076789    1
I182052372    1
Name: INCIDENT_NUMBER, Length: 98, dtype: int64

OFFENSE_CODE
413     76
111     20
3125    17
1501    14
2662    10
1510     6
1402     5
3001     5
3130     5
3114     4
423      3
1503     2
3115     2
1504     1
1845     1
3410     1
1874     1
301      1
381      1
Name: OFFENSE_CODE, dtype: int64

OFFENSE_CODE_GROUP
0     79
3     22
4     20
13    17
1     10
12     5
10     5
7      5
6      4
9      2
5      2
2      2
11     1
8      1
Name: OFFENSE_CODE_GROUP, dtype: int64

OFFENSE_DESCRIPTION
ASSAULT - AGGRAVATED - BATTERY                   76
MURDER, NON-NEGLIGIENT MANSLAUGHTER              20
WARRANT ARREST                                   17
WEAPON - FIREARM - CARRYING / POSSESSING, ETC    14
BALLISTICS EVIDENCE/FOUND                        10
WEAPON - FIREARM - OTHER VIOLATION                6
DEATH INVESTIGATION                               5
VANDALISM                                         5
SEARCH WARRANT                                    5
INVESTIGATE PROPERTY                              4
ASSAULT - AGGRAVATED                              3
INVESTIGATE PERSON                                2
WEAPON - OTHER - CARRYING / POSSESSING, ETC       2
WEAPON - OTHER - OTHER VIOLATION                  1
TOWED MOTOR VEHICLE                               1
ROBBERY - STREET                                  1
DRUGS - POSS CLASS D                              1
DRUGS - OTHER                                     1
ROBBERY - CAR JACKING                             1
Name: OFFENSE_DESCRIPTION, dtype: int64

DISTRICT
B2     63
B3     31
C11    31
E13    15
D4     11
D14     9
E18     7
C6      4
A15     2
E5      1
A1      1
Name: DISTRICT, dtype: int64

REPORTING_AREA
327    8
338    7
435    6
167    6
759    6
316    5
450    5
912    5
329    5
240    4
276    4
328    4
324    3
304    3
307    3
364    3
296    3
300    3
265    3
330    3
312    2
540    2
427    2
461    2
157    2
357    2
257    2
462    2
179    2
493    2
      ..
466    1
319    1
452    1
652    1
484    1
909    1
261    1
778    1
482    1
943    1
237    1
803    1
258    1
944    1
705    1
531    1
359    1
651    1
111    1
334    1
362    1
481    1
572    1
816    1
906    1
180    1
337    1
465    1
156    1
446    1
Name: REPORTING_AREA, Length: 82, dtype: int64

SHOOTING
Y    175
Name: SHOOTING, dtype: int64

OCCURRED_ON_DATE
27/04/2018 14:00    6
30/06/2018 00:41    6
8/6/18 15:00        5
25/06/2018 12:42    5
17/05/2018 21:24    5
25/07/2018 22:57    5
28/04/2018 02:45    4
24/09/2018 06:20    4
14/05/2018 22:28    4
21/05/2018 16:25    3
13/07/2018 14:01    3
4/7/18 21:50        3
4/5/18 5:07         3
24/02/2018 21:51    3
9/6/18 0:08         3
4/5/18 21:41        3
10/6/18 22:53       3
14/03/2018 16:12    3
22/08/2018 15:00    2
4/5/18 23:45        2
15/09/2018 03:35    2
29/09/2018 21:12    2
22/02/2018 00:13    2
7/7/18 15:06        2
15/09/2018 20:10    2
6/7/18 11:30        2
16/09/2018 03:17    2
8/8/18 1:07         2
29/08/2018 23:19    2
3/4/18 16:56        2
                   ..
4/8/18 22:53        1
4/8/18 2:12         1
23/06/2018 02:59    1
4/7/18 0:16         1
19/05/2018 01:35    1
19/02/2018 23:20    1
5/9/18 19:01        1
5/6/18 18:38        1
28/03/2018 01:05    1
3/7/18 23:39        1
15/08/2018 16:15    1
31/03/2018 15:55    1
5/4/18 23:38        1
12/8/18 22:52       1
25/02/2018 04:37    1
16/04/2018 13:02    1
31/07/2018 02:17    1
8/6/18 23:56        1
10/7/18 13:04       1
22/09/2018 21:46    1
25/03/2018 02:48    1
5/4/18 22:35        1
2/4/18 0:38         1
7/7/18 23:33        1
19/09/2018 14:18    1
22/07/2018 04:24    1
7/4/18 17:37        1
20/09/2018 17:10    1
30/07/2018 21:31    1
12/6/18 22:45       1
Name: OCCURRED_ON_DATE, Length: 98, dtype: int64

YEAR
2018    175
Name: YEAR, dtype: int64

MONTH
6    33
7    28
9    27
5    27
8    22
4    19
2    11
3     8
Name: MONTH, dtype: int64

DAY_OF_WEEK
2    44
6    35
1    30
0    25
5    15
3    15
4    11
Name: DAY_OF_WEEK, dtype: int64

HOUR
Night            66
Early Morning    47
Afternoon        35
Morning          14
Evening          13
Name: HOUR, dtype: int64

UCR_PART
Part One      101
Part Two       40
Part Three     34
Name: UCR_PART, dtype: int64

STREET
WASHINGTON ST             9
BRACKETT ST               6
CENTRE ST                 6
HARRISON AVE              6
NORFOLK ST                5
SOUTHERN AVE              5
BLUE HILL AVE             5
WINTER ST                 5
BISHOP JOE L SMITH WAY    5
WAYLAND ST                4
SHAWMUT AVE               4
HARTFORD ST               4
COLUMBIA RD               4
INTERVALE ST              4
COPELAND ST               3
BROOKFORD ST              3
WARREN ST                 3
HOLLANDER ST              2
FAYSTON ST                2
PATTERSON WAY             2
MCNULTY CT                2
HOMESTEAD ST              2
EVELYN ST                 2
STOCKTON ST               2
DORCHESTER AVE            2
WARDMAN RD                2
W NEWTON ST               2
CHURCH ST                 2
ABBOTSFORD ST             2
DRAPER ST                 2
                         ..
COSTELLO CIR              1
ROSA ST                   1
WESTMINSTER AVE           1
HEATH ST                  1
QUINCY ST                 1
CRAWFORD ST               1
HOPEWELL RD               1
AMES ST                   1
MONADNOCK ST              1
JULIAN ST                 1
EVANS ST                  1
PENNIMAN RD               1
HAMPDEN ST                1
EUSTIS ST                 1
DALESSIO CT               1
AKRON ST                  1
BICKFORD ST               1
CUMMINS HWY               1
W SPRINGFIELD ST          1
SPENCER ST                1
LAMARTINE ST              1
GLENARM ST                1
MURDOCK ST                1
MANSFIELD ST              1
ARCADIA ST                1
DEERING RD                1
WHITTIER ST               1
MANCHESTER ST             1
NEPONSET VALLEY PKWY      1
WILCOCK ST                1
Name: STREET, Length: 88, dtype: int64

Lat
42.339542    6
42.351987    6
42.288048    5
42.306604    5
42.309103    5
42.290866    5
42.315353    4
42.313689    4
42.332488    4
42.310499    4
42.319593    4
42.318415    3
42.322838    3
42.323808    3
42.316671    3
42.322216    3
42.295064    3
42.321948    3
42.315689    2
42.312421    2
42.298090    2
42.331400    2
42.293288    2
42.378085    2
42.314630    2
42.328830    2
42.250405    2
42.308597    2
42.315294    2
42.324241    2
            ..
42.261703    1
42.341870    1
42.333802    1
42.262173    1
42.307115    1
42.312845    1
42.314998    1
42.316681    1
42.337953    1
42.300226    1
42.274431    1
42.301550    1
42.305129    1
42.328296    1
42.295722    1
42.316339    1
42.323527    1
42.296852    1
42.325794    1
42.281060    1
42.302344    1
42.305532    1
42.262735    1
42.339711    1
42.291674    1
42.343091    1
42.241865    1
42.321042    1
42.296605    1
42.320229    1
Name: Lat, Length: 95, dtype: int64

Long
-71.165100    6
-71.069409    6
-71.062595    5
-71.080550    5
-71.077667    5
-71.072222    5
-71.062607    4
-71.083658    4
-71.074271    4
-71.077336    4
-71.073043    4
-71.082067    3
-71.089150    3
-71.081384    3
-71.097437    3
-71.100967    3
-71.056725    3
-71.076025    3
-71.071118    2
-71.091549    2
-71.077619    2
-71.094860    2
-71.089488    2
-71.062577    2
-71.051280    2
-71.071827    2
-71.075499    2
-71.091305    2
-71.084102    2
-71.081444    2
             ..
-71.072153    1
-71.136537    1
-71.077493    1
-71.097685    1
-71.075088    1
-71.096768    1
-71.110783    1
-71.088809    1
-71.071723    1
-71.100910    1
-71.091945    1
-71.068800    1
-71.147997    1
-71.132775    1
-71.092230    1
-71.085638    1
-71.062064    1
-71.102213    1
-71.072314    1
-71.070312    1
-71.102229    1
-71.096389    1
-71.082954    1
-71.074683    1
-71.085105    1
-71.056113    1
-71.076927    1
-71.062351    1
-71.064248    1
-71.078382    1
Name: Long, Length: 95, dtype: int64

Location
(42.33954199, -71.06940877)    6
(42.35198700, -71.16510001)    6
(42.29086554, -71.07222226)    5
(42.30660388, -71.08055038)    5
(42.30910324, -71.06259482)    5
(42.28804798, -71.07766654)    5
(42.31959298, -71.06260700)    4
(42.31368925, -71.07427080)    4
(42.31535276, -71.07304299)    4
(42.31049939, -71.07733579)    4
(42.33248759, -71.08365801)    4
(42.32194840, -71.08138427)    3
(42.31841535, -71.07602496)    3
(42.31667114, -71.09743705)    3
(42.32283759, -71.10096723)    3
(42.32380776, -71.08915023)    3
(42.29506405, -71.05672533)    3
(42.32221645, -71.08206723)    3
(42.34063708, -71.07572281)    2
(42.30859659, -71.06257749)    2
(42.30703587, -71.08410227)    2
(42.32882991, -71.08144379)    2
(42.31526714, -71.06306870)    2
(42.25040550, -71.13173740)    2
(42.29808992, -71.07178667)    2
(42.30540715, -71.06547135)    2
(42.31224327, -71.07549901)    2
(42.31242132, -71.09154902)    2
(42.28265604, -71.07374541)    2
(42.33176796, -71.07182739)    2
                              ..
(42.35752408, -71.13077384)    1
(42.35005321, -71.14799736)    1
(42.30234412, -71.07630370)    1
(42.30553202, -71.07031161)    1
(42.31284459, -71.09676806)    1
(42.31499803, -71.09194485)    1
(42.30455372, -71.08295366)    1
(42.33790280, -71.05611348)    1
(42.26506676, -71.09768522)    1
(42.32900380, -71.07838214)    1
(42.26273505, -71.11078287)    1
(42.24186532, -71.13277504)    1
(42.30438536, -71.07994459)    1
(42.30711484, -71.08425151)    1
(42.29572232, -71.07505157)    1
(42.27443147, -71.08131004)    1
(42.26170286, -71.10221348)    1
(42.34186952, -71.08372190)    1
(42.32104169, -71.07215291)    1
(42.33795319, -71.07749310)    1
(42.29990887, -71.06424768)    1
(42.35521429, -71.06206351)    1
(42.31633855, -71.06879992)    1
(42.30313990, -71.11735145)    1
(42.30022551, -71.07468313)    1
(42.32022882, -71.06307063)    1
(42.27404039, -71.07630093)    1
(42.29660463, -71.07692684)    1
(42.32610077, -71.10433335)    1
(42.26217287, -71.11245418)    1
Name: Location, Length: 95, dtype: int64

UCR_PART_Part One
1    101
0     74
Name: UCR_PART_Part One, dtype: int64

UCR_PART_Part Three
0    141
1     34
Name: UCR_PART_Part Three, dtype: int64

UCR_PART_Part Two
0    135
1     40
Name: UCR_PART_Part Two, dtype: int64

In [136]:
for col in data.columns:
    print(col)
    print(data[col].value_counts().unique())
    print()

INCIDENT_NUMBER
[6 5 4 3 2 1]

OFFENSE_CODE
[76 20 17 14 10  6  5  4  3  2  1]

OFFENSE_CODE_GROUP
[79 22 20 17 10  5  4  2  1]

OFFENSE_DESCRIPTION
[76 20 17 14 10  6  5  4  3  2  1]

DISTRICT
[63 31 15 11  9  7  4  2  1]

REPORTING_AREA
[8 7 6 5 4 3 2 1]

SHOOTING
[175]

OCCURRED_ON_DATE
[6 5 4 3 2 1]

YEAR
[175]

MONTH
[33 28 27 22 19 11  8]

DAY_OF_WEEK
[44 35 30 25 15 11]

HOUR
[66 47 35 14 13]

UCR_PART
[101  40  34]

STREET
[9 6 5 4 3 2 1]

Lat
[6 5 4 3 2 1]

Long
[6 5 4 3 2 1]

Location
[6 5 4 3 2 1]

UCR_PART_Part One
[101  74]

UCR_PART_Part Three
[141  34]

UCR_PART_Part Two
[135  40]

In [104]:
data

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182080058,2403,Disorderly Conduct,DISTURBING THE PEACE,E18,495,NaN,3/10/18 20:13,2018,10,Wednesday,20,Part Two,ARLINGTON ST,42.262608,-71.121186,"(42.26260773, -71.12118637)"
1,I182080053,3201,Property Lost,PROPERTY - LOST,D14,795,NaN,30/08/2018 20:00,2018,8,Thursday,20,Part Three,ALLSTON ST,42.352111,-71.135311,"(42.35211146, -71.13531147)"
2,I182080052,2647,Other,THREATS TO DO BODILY HARM,B2,329,NaN,3/10/18 19:20,2018,10,Wednesday,19,Part Two,DEVON ST,42.308126,-71.076930,"(42.30812619, -71.07692974)"
3,I182080051,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,92,NaN,3/10/18 20:00,2018,10,Wednesday,20,Part One,CAMBRIDGE ST,42.359454,-71.059648,"(42.35945371, -71.05964817)"
4,I182080050,3122,Aircraft,AIRCRAFT INCIDENTS,A7,36,NaN,3/10/18 20:49,2018,10,Wednesday,20,Part Three,PRESCOTT ST,42.375258,-71.024663,"(42.37525782, -71.02466343)"
5,I182080049,1402,Vandalism,VANDALISM,C11,351,NaN,2/10/18 20:40,2018,10,Tuesday,20,Part Two,DORCHESTER AVE,42.299197,-71.060470,"(42.29919694, -71.06046974)"
6,I182080048,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,NaN,ABC,NaN,3/10/18 20:16,2018,10,Wednesday,20,Part Three,NaN,42.320734,-71.056764,"(42.32073413, -71.05676415)"
7,I182080047,3301,Verbal Disputes,VERBAL DISPUTE,B2,603,NaN,3/10/18 19:32,2018,10,Wednesday,19,Part Three,TREMONT ST,42.333807,-71.103778,"(42.33380683, -71.10377843)"
8,I182080045,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,543,NaN,3/10/18 19:27,2018,10,Wednesday,19,Part Two,AVILA RD,42.256145,-71.128025,"(42.25614494, -71.12802506)"
9,I182080044,3410,Towed,TOWED MOTOR VEHICLE,D4,621,NaN,3/10/18 20:00,2018,10,Wednesday,20,Part Three,COMMONWEALTH AVE,42.348866,-71.089363,"(42.34886600, -71.08936284)"
10,I182080043,3803,Motor Vehicle Accident Response,M/V ACCIDENT - PERSONAL INJURY,D14,750,NaN,3/10/18 19:33,2018,10,Wednesday,19,Part Three,FOSTER ST,42.344323,-71.157784,"(42.34432328, -71.15778368)"
11,I182080042,706,Auto Theft,AUTO THEFT - MOTORCYCLE / SCOOTER,E13,582,NaN,1/10/18 20:00,2018,10,Monday,20,Part One,BYNNER ST,42.323244,-71.108923,"(42.32324363, -71.10892316)"
12,I182080041,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,E18,484,NaN,3/10/18 17:18,2018,10,Wednesday,17,Part Three,BELNEL RD,42.260599,-71.103061,"(42.26059891, -71.10306140)"
13,I182080040,3115,Investigate Person,INVESTIGATE PERSON,B3,427,NaN,3/10/18 8:00,2018,10,Wednesday,8,Part Three,ELIZABETH ST,42.279865,-71.087983,"(42.27986526, -71.08798275)"
14,I182080039,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,B3,469,NaN,3/10/18 19:58,2018,10,Wednesday,19,Part Three,FOTTLER RD,42.277919,-71.096406,"(42.27791927, -71.09640610)"
15,I182080038,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,NaN,XYZ,NaN,3/10/18 19:30,2018,10,Wednesday,19,Part Three,NaN,42.315961,-71.090426,"(42.31596119, -71.09042564)"
16,I182080037,2647,Other,THREATS TO DO BODILY HARM,C11,385,NaN,3/10/18 18:35,2018,10,Wednesday,18,Part Two,HALLET ST,42.280767,-71.047365,"(42.28076737, -71.04736497)"
17,I182080035,2647,Other,THREATS TO DO BODILY HARM,B2,326,NaN,3/10/18 19:56,2018,10,Wednesday,19,Part Two,DUNKELD ST,42.312778,-71.075629,"(42.31277782, -71.07562922)"
18,I182080034,3115,Investigate Person,INVESTIGATE PERSON,D4,626,NaN,3/10/18 18:41,2018,10,Wednesday,18,Part Three,KILMARNOCK ST,42.342681,-71.099377,"(42.34268073, -71.09937714)"
19,I182080031,3108,Fire Related Reports,"FIRE REPORT - HOUSE, BUILDING, ETC.",C11,338,NaN,3/10/18 18:18,2018,10,Wednesday,18,Part Three,NAVILLUS TER,42.309988,-71.062131,"(42.30998781, -71.06213111)"
20,I182080030,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,C6,234,NaN,2/10/18 20:00,2018,10,Tuesday,20,Part Three,COLUMBIA RD,42.330015,-71.038513,"(42.33001489, -71.03851306)"
21,I182080029,613,Larceny,LARCENY SHOPLIFTING,D4,146,NaN,3/10/18 19:09,2018,10,Wednesday,19,Part One,HUNTINGTON AVE,42.347972,-71.078496,"(42.34797240, -71.07849582)"
22,I182080028,3114,Investigate Property,INVESTIGATE PROPERTY,B2,295,NaN,3/10/18 18:24,2018,10,Wednesday,18,Part Three,HANSFORD ST,42.325276,-71.083516,"(42.32527567, -71.08351579)"
23,I182080027,3301,Verbal Disputes,VERBAL DISPUTE,B2,294,NaN,3/10/18 18:53,2018,10,Wednesday,18,Part Three,AKRON ST,42.325794,-71.085638,"(42.32579408, -71.08563758)"
24,I182080027,619,Larceny,LARCENY ALL OTHERS,B2,294,NaN,3/10/18 18:53,2018,10,Wednesday,18,Part One,AKRON ST,42.325794,-71.085638,"(42.32579408, -71.08563758)"
25,I182080026,2629,Harassment,HARASSMENT,C6,256,NaN,31/08/2017 00:00,2017,8,Thursday,0,Part Two,MOUNT VERNON ST,42.317794,-71.042110,"(42.31779354, -71.04210959)"
26,I182080025,311,Robbery,ROBBERY - COMMERCIAL,NaN,XCV,NaN,3/10/18 19:05,2018,10,Wednesday,19,Part One,NaN,42.349524,-71.079493,"(42.34952402, -71.07949284)"
27,I182080024,1842,Drug Violation,"DRUGS - POSS CLASS A - HEROIN, ETC.",E13,640,NaN,3/10/18 17:30,2018,10,Wednesday,17,Part Two,BOYLSTON ST,42.316942,-71.103946,"(42.31694189, -71.10394558)"
28,I182080023,3115,Investigate Person,INVESTIGATE PERSON,D4,165,NaN,12/5/18 0:00,2018,5,Saturday,0,Part Three,HARRISON AVE,42.342850,-71.065162,"(42.34285014, -71.06516235)"
29,I182080022,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,779,NaN,3/10/18 19:19,2018,10,Wednesday,19,Part Three,MONTCALM AVE,42.353211,-71.148411,"(42.35321122, -71.14841124)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65505,I182010090,1001,Counterfeiting,FORGERY / COUNTERFEITING,D14,798,NaN,1/4/16 9:00,2016,4,Friday,9,Part Two,COMMONWEALTH AVE,42.352168,-71.124571,"(42.35216801, -71.12457096)"
65506,I182010089,3114,Investigate Property,INVESTIGATE PROPERTY,B3,442,NaN,2/2/18 12:00,2018,2,Friday,12,Part Three,BERNARD ST,42.293509,-71.079913,"(42.29350931, -71.07991323)"
65507,I182010088,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,A7,26,NaN,7/2/18 15:47,2018,2,Wednesday,15,Part Three,MERIDIAN ST,42.379965,-71.039233,"(42.37996489, -71.03923314)"
65508,I182010087,613,Larceny,LARCENY SHOPLIFTING,C6,222,NaN,7/2/18 15:35,2018,2,Wednesday,15,Part One,E BROADWAY,42.335617,-71.036419,"(42.33561661, -71.03641895)"
65509,I182010086,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,C11,345,NaN,7/2/18 14:47,2018,2,Wednesday,14,Part Three,WESTVILLE ST,42.301387,-71.065842,"(42.30138747, -71.06584240)"
65510,I182010083,3114,Investigate Property,INVESTIGATE PROPERTY,C6,193,NaN,7/2/18 14:53,2018,2,Wednesday,14,Part Three,JENKINS ST,42.330469,-71.053374,"(42.33046940, -71.05337434)"
65511,I182010082,3201,Property Lost,PROPERTY - LOST,A1,111,NaN,2/2/18 5:30,2018,2,Friday,5,Part Three,AVERY ST,42.353260,-71.062832,"(42.35326010, -71.06283216)"
65512,I182010081,802,Simple Assault,ASSAULT SIMPLE - BATTERY,C6,194,NaN,7/2/18 15:11,2018,2,Wednesday,15,Part Two,DORCHESTER AVE,42.329717,-71.056968,"(42.32971683, -71.05696834)"
65513,I182010080,3115,Investigate Person,INVESTIGATE PERSON,E5,694,NaN,7/2/18 14:20,2018,2,Wednesday,14,Part Three,WELD ST,42.291834,-71.159141,"(42.29183428, -71.15914058)"
65514,I182010078,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,B3,440,NaN,7/2/18 15:23,2018,2,Wednesday,15,Part Three,BLUE HILL AVE,42.292788,-71.088519,"(42.29278843, -71.08851888)"
65515,I182010077,3301,Verbal Disputes,VERBAL DISPUTE,B3,418,NaN,7/2/18 14:08,2018,2,Wednesday,14,Part Three,FULLER ST,42.280728,-71.077136,"(42.28072751, -71.07713631)"
65516,I182010076,617,Larceny,LARCENY THEFT FROM BUILDING,A7,26,NaN,7/2/18 14:59,2018,2,Wednesday,14,Part One,BORDER ST,42.376203,-71.039799,"(42.37620267, -71.03979926)"
65517,I182010075,617,Larceny,LARCENY THEFT FROM BUILDING,E13,579,NaN,7/2/18 14:44,2018,2,Wednesday,14,Part One,CENTRE ST,42.322874,-71.101554,"(42.32287413, -71.10155354)"
65518,I182010075,1001,Counterfeiting,FORGERY / COUNTERFEITING,E13,579,NaN,7/2/18 14:44,2018,2,Wednesday,14,Part Two,CENTRE ST,42.322874,-71.101554,"(42.32287413, -71.10155354)"
65519,I182010074,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY DAMAGE,B2,290,NaN,7/2/18 14:24,2018,2,Wednesday,14,Part Three,TREMONT ST,42.332349,-71.093241,"(42.33234913, -71.09324099)"
65520,I182010073,2647,Other,THREATS TO DO BODILY HARM,E18,489,NaN,1/12/17 0:00,2017,12,Friday,0,Part Two,ROSEGLEN RD,42.266893,-71.108988,"(42.26689318, -71.10898767)"
65521,I182010072,724,Auto Theft,AUTO THEFT,C11,460,NaN,7/2/18 11:00,2018,2,Wednesday,11,Part One,COLUMBIA RD,42.305775,-71.079480,"(42.30577465, -71.07948006)"
65522,I182010071,2647,Other,THREATS TO DO BODILY HARM,E18,489,NaN,7/2/18 14:58,2018,2,Wednesday,14,Part Two,ROSEGLEN RD,42.266893,-71.108988,"(42.26689318, -71.10898767)"
65523,I182010071,2629,Harassment,HARASSMENT,E18,489,NaN,7/2/18 14:58,2018,2,Wednesday,14,Part Two,ROSEGLEN RD,42.266893,-71.108988,"(42.26689318, -71.10898767)"
65524,I182010069,3831,Motor Vehicle Accident Response,M/V - LEAVING SCENE - PROPERTY DAMAGE,A7,26,NaN,7/2/18 14:07,2018,2,Wednesday,14,Part Three,MERIDIAN ST,42.371729,-71.039000,"(42.37172932, -71.03899985)"
65525,I182010068,3201,Property Lost,PROPERTY - LOST,A7,10,NaN,29/11/2017 19:30,2017,11,Wednesday,19,Part Three,SARATOGA ST,42.386855,-71.007383,"(42.38685489, -71.00738288)"
65526,I182010067,2608,Offenses Against Child / Family,CHINS,A15,900,NaN,7/2/18 13:26,2018,2,Wednesday,13,Part Two,POLK ST,42.379127,-71.061227,"(42.37912706, -71.06122663)"
65527,I182010065,3801,Motor Vehicle Accident Response,M/V ACCIDENT - OTHER,C11,346,NaN,7/2/18 14:07,2018,2,Wednesday,14,Part Three,ADAMS ST,42.306004,-71.061782,"(42.30600379, -71.06178187)"
65528,I182010064,614,Larceny From Motor Vehicle,LARCENY THEFT FROM MV - NON-ACCESSORY,E13,650,NaN,6/2/18 19:00,2018,2,Tuesday,19,Part One,JAMAICA PL,42.305817,-71.119087,"(42.30581739, -71.11908749)"
65529,I182010063,615,Larceny From Motor Vehicle,LARCENY THEFT OF MV PARTS & ACCESSORIES,B2,301,NaN,2/2/18 17:00,2018,2,Friday,17,Part One,FORT AVE,42.325912,-71.094948,"(42.32591192, -71.09494763)"
65530,I182010062,3301,Verbal Disputes,VERBAL DISPUTE,C6,936,NaN,7/2/18 13:11,2018,2,Wednesday,13,Part Three,W SEVENTH ST,42.336979,-71.055003,"(42.33697857, -71.05500277)"
65531,I182010061,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,E13,930,NaN,7/2/18 13:17,2018,2,Wednesday,13,Part Three,COLUMBUS AVE,42.315069,-71.097466,"(42.31506898, -71.09746579)"
65532,I182010060,3305,Assembly or Gathering Violations,DEMONSTRATIONS/RIOT,A1,111,NaN,7/2/18 11:54,2018,2,Wednesday,11,Part Three,TREMONT ST,42.354284,-71.063804,"(42.35428377, -71.06380404)"
65533,I182010058,1841,Drug Violation,DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP,C11,402,NaN,7/2/18 14:13,2018,2,Wednesday,14,Part Two,ROCKWELL ST,42.283875,-71.071550,"(42.28387495, -71.07154989)"
65534,I182010058,3115,Investigate Person,INVESTIGATE PERSON,C11,402,NaN,7/2/18 14:13,2018,2,Wednesday,14,Part Three,ROCKWELL ST,42.283875,-71.071550,"(42.28387495, -71.07154989)"

In [105]:
data["INCIDENT_NUMBER"].duplicated().sum()

7302

In [106]:
data["INCIDENT_NUMBER"].drop_duplicates(keep="last", inplace=True)

In [107]:
data["OFFENSE_CODE_GROUP"].value_counts()

Motor Vehicle Accident Response     7572
Medical Assistance                  5527
Larceny                             5295
Investigate Person                  3747
Other                               3746
Simple Assault                      3500
Drug Violation                      3192
Verbal Disputes                     2992
Vandalism                           2801
Towed                               2642
Investigate Property                2549
Property Lost                       2418
Larceny From Motor Vehicle          2042
Aggravated Assault                  1661
Fraud                               1447
Violations                          1178
Warrant Arrests                     1042
Missing Person Located               960
Auto Theft                           927
Property Found                       913
Residential Burglary                 868
Harassment                           849
Robbery                              774
Police Service Incidents             755
Missing Person Reported              675
Confidence Games                     564
Disorderly Conduct                   441
Fire Related Reports                 394
Firearm Violations                   341
License Violation                    338
Restraining Order Violations         311
Recovered Stolen Property            292
Liquor Violation                     255
Counterfeiting                       241
Landlord/Tenant Disputes             227
Auto Theft Recovery                  216
Commercial Burglary                  203
Property Related Damage              184
Ballistics                           183
Search Warrants                      151
Assembly or Gathering Violations     143
License Plate Related Incidents      129
Firearm Discovery                    116
Offenses Against Child / Family      100
Operating Under the Influence         92
Evading Fare                          86
Other Burglary                        84
Prisoner Related Incidents            64
Embezzlement                          58
Service                               57
Harbor Related Incidents              57
Homicide                              30
Criminal Harassment                   29
HOME INVASION                         17
Arson                                 15
Bomb Hoax                             11
Prostitution                          11
Phone Call Complaints                 10
Explosives                             7
Aircraft                               6
Name: OFFENSE_CODE_GROUP, dtype: int64

In [108]:
data["REPORTING_AREA"].value_counts()

        4689
111      511
186      469
624      428
329      400
465      389
26       358
143      345
117      322
175      318
427      306
134      305
130      300
304      296
520      291
627      289
428      286
900      285
337      282
282      282
355      274
311      273
914      246
444      243
330      241
328      237
288      237
177      235
170      234
94       232
        ...
683        4
672        4
744        4
505        4
708        4
739        4
753        4
595        4
665        3
689        3
741        3
743        3
663        3
599        3
690        3
678        2
927        2
960        2
671        2
698        2
917        2
819        1
0          1
 ttt       1
218        1
XCV        1
 ABC       1
277        1
745        1
 XYZ       1
Name: REPORTING_AREA, Length: 880, dtype: int64

In [109]:
cnt=0
for row in data['REPORTING_AREA']:
    if(len(str(row))!=3)or (any(c.isalpha()for c in row)):
        data.loc[cnt,'REPORTING_AREA']=np.nan
    cnt+=1

In [110]:
data["REPORTING_AREA"].head()

0    495
1    795
2    329
3    NaN
4    NaN
Name: REPORTING_AREA, dtype: object

In [111]:
data["YEAR"].value_counts()

2018    65146
2017      326
2016       47
2015       16
Name: YEAR, dtype: int64

In [112]:
data['MONTH'].value_counts()

5     8947
6     8893
8     8659
7     8626
9     8176
4     7923
3     7739
2     5492
10     741
1      206
12      83
11      50
Name: MONTH, dtype: int64

In [113]:
data["DAY_OF_WEEK"].value_counts()

Friday       9975
Wednesday    9712
Thursday     9712
Tuesday      9419
Monday       9327
Saturday     9197
Sunday       8193
Name: DAY_OF_WEEK, dtype: int64

In [114]:
data["UCR_PART"].value_counts()

Part Three    33755
Part Two      19615
Part One      11884
Other           264
Name: UCR_PART, dtype: int64

In [115]:
data.dropna(axis=0,inplace=True)
data.reset_index(drop=True, inplace=True )

In [116]:
data.shape

(175, 17)

In [117]:
data.dropna(axis=1, thresh=0.50*len(data),inplace=True)
data.reset_index(drop=True, inplace=True )

In [118]:
data.shape

(175, 17)

In [119]:
data.isnull().sum()

INCIDENT_NUMBER        0
OFFENSE_CODE           0
OFFENSE_CODE_GROUP     0
OFFENSE_DESCRIPTION    0
DISTRICT               0
REPORTING_AREA         0
SHOOTING               0
OCCURRED_ON_DATE       0
YEAR                   0
MONTH                  0
DAY_OF_WEEK            0
HOUR                   0
UCR_PART               0
STREET                 0
Lat                    0
Long                   0
Location               0
dtype: int64

# Feature Encoding and Discretization

1. Apply label encoding to OFFENSE_CODE_GROUP and DAY_OF_WEEK
2. Apply One-Hot Encoding to UCR_PART
3. Apply Discretization to HOUR (0-8 Early Morning , 8-12 Morning 12-16 Afternoon, 16-19 Evening, 19-23 Night) or you can create your own levels.

In [120]:
from numpy import array
from sklearn.preprocessing import LabelEncoder

In [121]:
data.head(3)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182078893,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,C11,416,Y,29/09/2018 21:12,2018,9,Saturday,21,Part One,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
1,I182078893,2662,Ballistics,BALLISTICS EVIDENCE/FOUND,C11,416,Y,29/09/2018 21:12,2018,9,Saturday,21,Part Two,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
2,I182078872,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,B2,330,Y,29/09/2018 19:21,2018,9,Saturday,19,Part One,SEAVER ST,42.304554,-71.082954,"(42.30455372, -71.08295366)"

In [122]:
label_encoder = LabelEncoder()
data["OFFENSE_CODE_GROUP"] = label_encoder.fit_transform(data["OFFENSE_CODE_GROUP"])
data.head(3)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182078893,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,416,Y,29/09/2018 21:12,2018,9,Saturday,21,Part One,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
1,I182078893,2662,1,BALLISTICS EVIDENCE/FOUND,C11,416,Y,29/09/2018 21:12,2018,9,Saturday,21,Part Two,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
2,I182078872,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,330,Y,29/09/2018 19:21,2018,9,Saturday,19,Part One,SEAVER ST,42.304554,-71.082954,"(42.30455372, -71.08295366)"

In [123]:
data['DAY_OF_WEEK'] = label_encoder.fit_transform(data['DAY_OF_WEEK'])
data.head(3)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182078893,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,416,Y,29/09/2018 21:12,2018,9,2,21,Part One,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
1,I182078893,2662,1,BALLISTICS EVIDENCE/FOUND,C11,416,Y,29/09/2018 21:12,2018,9,2,21,Part Two,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)"
2,I182078872,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,330,Y,29/09/2018 19:21,2018,9,2,19,Part One,SEAVER ST,42.304554,-71.082954,"(42.30455372, -71.08295366)"

In [124]:
data.columns

Index(['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP',
       'OFFENSE_DESCRIPTION', 'DISTRICT', 'REPORTING_AREA', 'SHOOTING',
       'OCCURRED_ON_DATE', 'YEAR', 'MONTH', 'DAY_OF_WEEK', 'HOUR', 'UCR_PART',
       'STREET', 'Lat', 'Long', 'Location'],
      dtype='object')

In [125]:
data['UCR_PART'].dtypes

dtype('O')

In [126]:
data['UCR_PART'] = pd.Categorical(data['UCR_PART'])

In [128]:
dummy = pd.get_dummies(data['UCR_PART'], prefix = 'UCR_PART')

In [129]:
dummy.head()

   UCR_PART_Part One  UCR_PART_Part Three  UCR_PART_Part Two
0                  1                    0                  0
1                  0                    0                  1
2                  1                    0                  0
3                  1                    0                  0
4                  0                    0                  1

In [130]:
data = pd.concat([data, dummy], axis=1)

In [131]:
data.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location,UCR_PART_Part One,UCR_PART_Part Three,UCR_PART_Part Two
0,I182078893,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,416,Y,29/09/2018 21:12,2018,9,2,21,Part One,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)",1,0,0
1,I182078893,2662,1,BALLISTICS EVIDENCE/FOUND,C11,416,Y,29/09/2018 21:12,2018,9,2,21,Part Two,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)",0,0,1
2,I182078872,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,330,Y,29/09/2018 19:21,2018,9,2,19,Part One,SEAVER ST,42.304554,-71.082954,"(42.30455372, -71.08295366)",1,0,0
3,I182077958,413,0,ASSAULT - AGGRAVATED - BATTERY,B3,428,Y,26/09/2018 20:20,2018,9,6,20,Part One,MORTON ST,42.283746,-71.089382,"(42.28374593, -71.08938232)",1,0,0
4,I182077958,2662,1,BALLISTICS EVIDENCE/FOUND,B3,428,Y,26/09/2018 20:20,2018,9,6,20,Part Two,MORTON ST,42.283746,-71.089382,"(42.28374593, -71.08938232)",0,0,1

Apply Discretization to HOUR (0-8 Early Morning , 8-12 Morning 12-16 Afternoon, 16-19 Evening, 19-23 Night) or you can create your own levels.

In [132]:
data['HOUR']  = np.where((data['HOUR'] <8) ,'Early Morning',
                               np.where((data['HOUR'] >=8) & (data['HOUR'] <=12),'Morning',
                               np.where((data['HOUR']>12) & (data['HOUR'] <=16),'Afternoon',
                               np.where((data['HOUR']>16) & (data['HOUR'] <=19),'Evening',
                                       'Night'))))

In [133]:
data.head(19)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location,UCR_PART_Part One,UCR_PART_Part Three,UCR_PART_Part Two
0,I182078893,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,416,Y,29/09/2018 21:12,2018,9,2,Night,Part One,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)",1,0,0
1,I182078893,2662,1,BALLISTICS EVIDENCE/FOUND,C11,416,Y,29/09/2018 21:12,2018,9,2,Night,Part Two,WASHINGTON ST,42.281647,-71.071118,"(42.28164735, -71.07111848)",0,0,1
2,I182078872,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,330,Y,29/09/2018 19:21,2018,9,2,Evening,Part One,SEAVER ST,42.304554,-71.082954,"(42.30455372, -71.08295366)",1,0,0
3,I182077958,413,0,ASSAULT - AGGRAVATED - BATTERY,B3,428,Y,26/09/2018 20:20,2018,9,6,Night,Part One,MORTON ST,42.283746,-71.089382,"(42.28374593, -71.08938232)",1,0,0
4,I182077958,2662,1,BALLISTICS EVIDENCE/FOUND,B3,428,Y,26/09/2018 20:20,2018,9,6,Night,Part Two,MORTON ST,42.283746,-71.089382,"(42.28374593, -71.08938232)",0,0,1
5,I182077113,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,276,Y,24/09/2018 06:20,2018,9,1,Early Morning,Part One,SHAWMUT AVE,42.332488,-71.083658,"(42.33248759, -71.08365801)",1,0,0
6,I182077113,1510,3,WEAPON - FIREARM - OTHER VIOLATION,B2,276,Y,24/09/2018 06:20,2018,9,1,Early Morning,Part Two,SHAWMUT AVE,42.332488,-71.083658,"(42.33248759, -71.08365801)",0,0,1
7,I182077113,3130,10,SEARCH WARRANT,B2,276,Y,24/09/2018 06:20,2018,9,1,Early Morning,Part Three,SHAWMUT AVE,42.332488,-71.083658,"(42.33248759, -71.08365801)",0,1,0
8,I182077113,1501,3,"WEAPON - FIREARM - CARRYING / POSSESSING, ETC",B2,276,Y,24/09/2018 06:20,2018,9,1,Early Morning,Part Two,SHAWMUT AVE,42.332488,-71.083658,"(42.33248759, -71.08365801)",0,0,1
9,I182076987,413,0,ASSAULT - AGGRAVATED - BATTERY,D4,156,Y,23/09/2018 13:53,2018,9,3,Afternoon,Part One,W SPRINGFIELD ST,42.337953,-71.077493,"(42.33795319, -71.07749310)",1,0,0
10,I182076789,111,4,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",E13,651,Y,22/09/2018 21:46,2018,9,2,Night,Part One,SOUTH ST,42.305129,-71.114619,"(42.30512949, -71.11461873)",1,0,0
11,I182076074,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,334,Y,20/09/2018 17:10,2018,9,4,Evening,Part One,QUINCY ST,42.309470,-71.066644,"(42.30947016, -71.06664424)",1,0,0
12,I182075690,413,0,ASSAULT - AGGRAVATED - BATTERY,B2,261,Y,19/09/2018 14:18,2018,9,6,Afternoon,Part One,JULIAN ST,42.318947,-71.074528,"(42.31894677, -71.07452770)",1,0,0
13,I182074638,3114,6,INVESTIGATE PROPERTY,D4,157,Y,16/09/2018 03:17,2018,9,3,Early Morning,Part Three,W NEWTON ST,42.340637,-71.075723,"(42.34063708, -71.07572281)",0,1,0
14,I182074638,413,0,ASSAULT - AGGRAVATED - BATTERY,D4,157,Y,16/09/2018 03:17,2018,9,3,Early Morning,Part One,W NEWTON ST,42.340637,-71.075723,"(42.34063708, -71.07572281)",1,0,0
15,I182074555,111,4,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",B2,330,Y,15/09/2018 20:10,2018,9,2,Night,Part One,BLUE HILL AVE,42.307036,-71.084102,"(42.30703587, -71.08410227)",1,0,0
16,I182074555,3115,5,INVESTIGATE PERSON,B2,330,Y,15/09/2018 20:10,2018,9,2,Night,Part Three,BLUE HILL AVE,42.307036,-71.084102,"(42.30703587, -71.08410227)",0,1,0
17,I182074372,413,0,ASSAULT - AGGRAVATED - BATTERY,C11,257,Y,15/09/2018 03:35,2018,9,2,Early Morning,Part One,EVERETT AVE,42.315267,-71.063069,"(42.31526714, -71.06306870)",1,0,0
18,I182074372,2662,1,BALLISTICS EVIDENCE/FOUND,C11,257,Y,15/09/2018 03:35,2018,9,2,Early Morning,Part Two,EVERETT AVE,42.315267,-71.063069,"(42.31526714, -71.06306870)",0,0,1